config/routes.rb
Rails.application.routes.draw do

  get 'welcomes/index'
  get 'abouts/index'
  resources :companies, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :departments, only: [:index], controller: 'companies/departments'
  end
  resources :departments, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :employees, only: [:index, :cut], controller: 'departments/employees' do
      collection do
        post :cut
      end
    end
  end
  resources :employees, only: [:index, :new, :create, :edit, :update, :destroy, :cut] do
    collection do
      post :cut
    end
  end

  root 'welcomes#index'

end

app/models/company.rb
#Developer: Marius
#one company got many departments and if you delete the company, you delete the dependencies as well

class Company < ActiveRecord::Base
  # === Associations ===
  has_many :departments, dependent: :destroy
  has_many :employees, through: :departments

  #a company must have a name
  # === Validations ===
  validates :name, presence: true
end

app/models/department.rb
#Developer: Marius
#One department got many employees and many sub departments
#One department got only one super department, one manager and one company

class Department < ActiveRecord::Base
# === Associations ===
  has_many :employees
  has_many :sub_departments, class_name: 'Department', dependent: :destroy, foreign_key: 'super_department_id'
  belongs_to :super_department, class_name: 'Department'
  belongs_to :manager, class_name: 'Employee'
  belongs_to :company

  #a department must have a name
  # === Validations ===
  validates :name, presence: true

end

app/models/employee.rb
# Developer: Marius
# An Employee has one department

class Employee < ActiveRecord::Base
  # === Associations ===
  belongs_to :department

  # An Employee must have a name and a salary
  # === Validations ===
  validates :name, presence: true
  validates :salary, numericality: true

  # cut-feature halfs the salary of the employee
  def cut
    self.salary /= 2
    self.save
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  #only static content, no need for ruby
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies/departments_controller.rb
class Companies::DepartmentsController < ApplicationController
  #Developer: Marco&Marius

  # === Callbacks ===
  before_action :set_company, only: [:index]


  def index
    @departments = Department.where(company_id: @company.id)
  end

  private

  def set_company
    @company = Company.includes(:departments).find(params[:company_id])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  #Developer: Marco&Marius

  # === Callbacks ===
  before_action :set_companies, only: [:index]
  before_action :set_company, only: [:edit, :update, :destroy]

  def index

  end

  def new
    @company = Company.new
    render layout: false
  end

  def create
    @company = Company.create(company_params)
  end

  def edit
    render layout: false
  end

  def update
    @company.update(company_params)
    set_company
  end

  def destroy
    @company.destroy
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def set_companies
    @companies = Company.all
  end

  def company_params
    params.require(:company).permit(:name)
  end

  def set_departments
    @departments = Department.where(company_id: params[:id])
  end
end

app/controllers/departments/employees_controller.rb
class Departments::EmployeesController < ApplicationController
  # Developer: Marco & Marius

  # === Callbacks ===
  before_action :set_department, only: [:index, :cut]

  def index
    @employees = Employee.where(department_id: @department.id)
  end

  def cut
    set_employees
    employees_id_array = params[:format].split('/')
    if employees_id_array.size == 1
      @employee = Employee.where(id: employees_id_array)
      cut_salaries(@employee)
    else
      cut_salaries(@employees)
    end
    @employees.reload
  end

  private

  def cut_salaries(employees)
    unless employees.nil?
      employees.each do |e|
        e.cut
      end
    end
  end

  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_employees
    @employees = Employee.where(department_id: @department.id)
  end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  #Developer: Marco&Marius

  # === Callbacks ===
  before_action :set_departments, only: [:index, :new, :edit]
  before_action :set_companies, only: [:new, :edit]
  before_action :set_employees, only: [:new, :edit]
  before_action :set_department, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @department = Department.new
    render layout: false
  end

  def create
    @department = Department.create(department_params)
  end

  def edit
    render layout: false
  end

  def update
    @department.update(department_params)
    set_department
  end

  def destroy
    @department.destroy
  end

  private

  def set_department
    @department = Department.find(params[:id])
  end

  def set_departments
    @departments = Department.all
  end

  def set_companies
    @companies = Company.all
  end

  def set_employees
    @employees = Employee.where(department_id: params[:id])
  end

  def department_params
    params.require(:department).permit(:name, :company_id, :super_department_id, :manager_id)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # Developer: Marco & Marius

  # === Callbacks ===
  before_action :set_employees, only: [:index, :create, :update]
  before_action :set_departments, only: [:new, :edit]
  before_action :set_employee, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @employee = Employee.new
    render layout: false
  end

  def create
    @employee = Employee.create(employee_params)
  end

  def edit
    render layout: false
  end

  def update
    @employee.update(employee_params)
    set_employee
    set_employees
  end

  def destroy
    @employee.destroy
    set_employees
  end

  def cut
    set_employees
    employees_id_array = params[:format].split('/')
    if employees_id_array.size == 1
      @employee = Employee.where(id: employees_id_array)
      cut_salaries(@employee)
    else
      cut_salaries(@employees)
    end
    @employees.reload
  end

  private

  def cut_salaries(employees)
    unless employees.nil?
      employees.each do |e|
        e.cut
      end
    end
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def set_employees
    @employees = Employee.all
  end

  def set_departments
    @departments = Department.all
  end

  def employee_params
    params.require(:employee).permit(:name, :address, :salary, :department_id)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  # Developer : Frank & André

  # returns the number of employees for a chosen company or department
  def get_employee_count(unit)
    result = 0
    begin
      unit.departments.each do |department|
        result += department.employees.count
      end
    rescue
      result = unit.employees.count
    end
    result
  end

  # returns the number of departments of a company
  def get_department_count(company)
    company.departments.count
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper

end

app/helpers/employees_helper.rb
module EmployeesHelper
  #Developer : André & Frank

  # return total salary of the given collection employees
  def get_total_salaries(employees)
    total = 0
    employees.each do |e|
      unless e.salary.nil?
        total += e.salary
      end
    end
    total.round(2)
  end

  # returns the average salary of the given collection employees
  def get_mean_salary(employees)
    if employees.count != 0
      (get_total_salaries(employees) / employees.count).round(2)
    else
      0
    end
  end

end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/abouts/index.html.erb
<!--Developer: Isabelle&Diana-->

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>About CompanyManager</h3>

      <div class="container">
        <p><a href="http://softlang.wikidot.com/course:ptt16">Course Wiki</a></p>

        <p><a href="https://gitlab.uni-koblenz.de/turing16/tyrion">Gitlab Repository</a></p>

        <p><a href="https://github.com/fuuman/101company">Our Code on Github</a></p>

        <p>The web application <i>CompanyManager</i> was created by the Group <b>turing16/tyrion</b> in the
          context of the course "Programming techniques and technologies" (SS2016) at the University Koblenz-Landau.</p>

        <p style="margin-top: 25px"><h4>Group members:</h4>
        <ul class="container">
          <li>Marco Schanz</li>
          <li>Isabelle Kuhlmann</li>
          <li>Diana Richter</li>
          <li>Marius Beckmann</li>
          <li>Frank Schaust</li>
          <li>André-Gilbert Thomas</li>
        </ul>
        </p>

      </div>
    </div>
  </div>
</div>

app/views/companies/create.js.erb
$('#company_modal').modal('hide')
$('#company_table').find('tbody').append('<%= j render partial: 'companies/partials/company', locals: {company: @company} %>')

app/views/companies/departments/index.html.erb
<div class="container">
  <% if @departments.empty? %>
      <div class="alert alert-danger" role="alert">
        <strong>Sorry!</strong> This company doesn't have any departments.
      </div>
  <% else %>
      <div class="container">
        <h3>Departments of <%= @departments.first.company.name %></h3>

        <%= render partial: 'departments/partials/department_table', locals: {departments: @departments} %>
      </div>
  <% end %>
</div>
<div id="department_modal" class="modal fade" role="dialog"></div>

app/views/companies/destroy.js.erb
$('#company_<%= @company.id %>').fadeOut(function() {$(this).remove()});

app/views/companies/edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
      <h4 class="modal-title custom_align" id="Heading">Edit company</h4>
    </div>
    <div class="modal-body">
      <%= render partial: 'companies/partials/form', locals: {company: @company} %>
    </div>
  </div>
  <!-- /.modal-content -->
</div>

app/views/companies/index.html.erb
<%= render partial: 'companies/partials/company_table', locals: {companies: @companies} %>
<div id="company_modal" class="modal fade" role="dialog"></div>

app/views/companies/new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
      <h4 class="modal-title custom_align" id="Heading">Create new company</h4>
    </div>
    <div class="modal-body">
      <%= render partial: 'companies/partials/form', locals: {company: @company} %>
    </div>
  </div>
  <!-- /.modal-content -->
</div>

app/views/companies/partials/_company.html.erb
<tr id="company_<%= company.id %>">
  <td><%= link_to company.name, company_departments_path(company) %></td>
  <td><%= get_department_count(company) %></td>
  <td><%= get_employee_count(company) %></td>
  <td><%= '%.2f' % get_mean_salary(company.employees) %></td>
  <td><%= '%.2f' % get_total_salaries(company.employees) %></td>
  <td>
    <p data-placement="top" data-toggle="tooltip" title="Edit">
      <button class="btn btn-primary btn-xs" id="edit_company_<%= company.id %>">
        <span class="glyphicon glyphicon-pencil"></span></button>
    </p>
  </td>
  <td>
    <%= link_to company, method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
        <p data-placement="top" data-toggle="tooltip" title="Delete">
          <button class="btn btn-danger btn-xs">
            <span class="glyphicon glyphicon-trash"></span></button>
        </p>
    <% end %>
  </td>
</tr>
<script>$(function () {
  var $modal = $('#company_modal');
  $('#edit_company_<%= company.id %>').on('click', function () {
    $modal.load('<%= edit_company_path(company) %>', '', function () {
      $modal.modal();
    });
  });
});</script>

app/views/companies/partials/_company_table.html.erb
<div class="container">
  <div class="row">


    <div class="col-md-12">
      <h3>Companies</h3>
      <p><button type="button" id="new_company" class="btn btn-primary mybuttons">Create new company</button></p>
      <div class="table-responsive">


        <table id="company_table" class="table table-bordred table-striped">

          <thead>
          <tr>
            <th>Name</th>
            <th># Departments</th>
            <th># Employees</th>
            <th>Mean Salary</th>
            <th>Total Salary</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>

          <% companies.each do |company| %>
              <%= render partial: 'companies/partials/company', locals: {company: company} %>
          <% end %>

          </tbody>

        </table>

      </div>
    </div>
  </div>
</div>
</div>
<script>$(function () {
  var $modal = $('#company_modal');
  $('#new_company').on('click', function () {
    $modal.load('<%= new_company_path %>', '', function () {
      $modal.modal();
    });
  });
});</script>

app/views/companies/partials/_form.html.erb
<%= form_for company, remote: true, html: {id: 'company_form'} do |f| %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
      <span class="help-block"></span>
    </p>
    <p>
      <%= f.submit nil, class: 'btn btn-warning' %>
    </p>
<% end %>
<script>
  $(function () {
    var $form = $('#company_form');
    $form.validate({
      rules: {
        "company[name]": {
          required: true
        }
      },
      errorPlacement: function (error, element) {
        $(element).closest('p').find('.help-block').text(error.text());
      },
      highlight: function (element) {
        $(element).closest('p').removeClass('has-success');
        $(element).closest('p').addClass('has-error');
      },
      unhighlight: function (element) {
        $(element).closest('p').removeClass('has-error');
      },
      success: function (element) {
        $(element).closest('p').addClass('has-success');
      }
    });
  });
</script>

app/views/companies/update.js.erb
$('#company_modal').modal('hide')
$('#company_<%= @company.id %>').replaceWith('<%= j render partial: 'companies/partials/company', locals: {company: @company} %>')

app/views/departments/employees/cut.js.erb
$('#employee_table').replaceWith('<%= j render partial: 'employees/partials/employee_table', locals: {employees: @employees} %>');
$('#salary_statistics').replaceWith('<%= j render partial: 'employees/partials/statistics', locals: {employees: @employees} %>');

app/views/departments/employees/index.html.erb
<div class="container">
  <% if @employees.empty? %>
      <div class="alert alert-danger" role="alert">
        <strong>Sorry!</strong> This department doesn't have any employees.
      </div>
  <% else %>
      <div class="container">
        <h3>Employees of <%= @employees.first.department.name %></h3>

        <div style="margin-bottom: -10px; margin-top: 30px">
          <%= render partial: 'employees/partials/statistics', locals: {employees: @employees} %>
        </div>

        <%= link_to cut_department_employees_path(department_id: @department.id, format: @employees.pluck(:id)), method: :post, remote: true do %>

            <button type="button" class="btn btn-warning mybuttons">Cut all salaries</button>

        <% end %>

        <%= render partial: 'employees/partials/employee_table', locals: {employees: @employees} %>
      </div>
  <% end %>
</div>
<div id="employee_modal" class="modal fade" role="dialog"></div>

app/views/departments/partials/_department.html.erb
<tr id="department_<%= department.id %>">
  <td><%= if department.employees.nil? then department.name else link_to department.name, department_employees_path(department) end %></td>
  <td><%= link_to department.company.name, company_departments_path(department.company) if department.company.present? %></td>
  <td><%= department.manager.name rescue '' %></td>
  <td><%= get_employee_count(department) %></td>
  <td><%= '%.2f' % get_mean_salary(department.employees) %></td>
  <td><%= '%.2f' % get_total_salaries(department.employees) %></td>
  <td>
    <p data-placement="top" data-toggle="tooltip" title="Edit">
      <button class="btn btn-primary btn-xs" id="edit_department_<%= department.id %>">
        <span class="glyphicon glyphicon-pencil"></span></button>
    </p>
  </td>
  <td>
    <%= link_to department, method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
        <p data-placement="top" data-toggle="tooltip" title="Delete">
          <button class="btn btn-danger btn-xs">
            <span class="glyphicon glyphicon-trash"></span></button>
        </p>
    <% end %>
  </td>
</tr>
<script>$(function () {
  var $modal = $('#department_modal');
  $('#edit_department_<%= department.id %>').on('click', function () {
    $modal.load('<%= edit_department_path(department) %>', '', function () {
      $modal.modal();
    });
  });
});</script>

app/views/departments/partials/_department_table.html.erb
<table id="department_table" class="table table-bordred table-striped">

  <thead>
  <tr>
    <th>Name</th>
    <th>Company</th>
    <th>Manager</th>
    <th># Employees</th>
    <th>Mean salary</th>
    <th>Total salary</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>

  <% departments.each_with_index do |department| %>
      <%= render partial: 'departments/partials/department', locals: {department: department} %>
  <% end %>

  </tbody>

</table>

<script>$(function () {
  var $modal = $('#department_modal');
  $('#new_department').on('click', function () {
    $modal.load('<%= new_department_path %>', '', function () {
      $modal.modal();
    });
  });
});</script>

app/views/departments/partials/_form.html.erb
<%= form_for department, remote: true, html: {id: 'department_form'} do |f| %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
      <span class="help-block"></span>
    </p>
    <p>
      <%= f.label :company_id %><br/>
      <%= f.select :company_id, options_from_collection_for_select(companies, :id, :name, f.object.company_id), include_blank: '' %>
    </p>
    <p>
      <%= f.label :super_department_id %><br/>
      <%= f.select :super_department_id, options_from_collection_for_select(departments, :id, :name, f.object.super_department_id), include_blank: '' %>
    </p>
    <p>
      <%= f.label :manager_id %><br/>
      <%= f.select :manager_id, options_from_collection_for_select(employees, :id, :name, f.object.manager_id), include_blank: '' %>
    </p>
    <p>
      <%= f.submit nil, class: 'btn btn-warning' %>
    </p>
<% end %>
<script>
  $(function () {
    var $form = $('#department_form');
    $form.validate({
      rules: {
        "department[name]": {
          required: true
        }
      },
      errorPlacement: function (error, element) {
        $(element).closest('p').find('.help-block').text(error.text());
      },
      highlight: function (element) {
        $(element).closest('p').removeClass('has-success');
        $(element).closest('p').addClass('has-error');
      },
      unhighlight: function (element) {
        $(element).closest('p').removeClass('has-error');
      },
      success: function (element) {
        $(element).closest('p').addClass('has-success');
      }
    });
  });
</script>

app/views/employees/create.js.erb
$('#employee_modal').modal('hide');
$('#employee_table').find('tbody').append('<%= j render partial: 'employees/partials/employee', locals: {employee: @employee} %>');
$('#salary_statistics').replaceWith('<%= j render partial: 'employees/partials/statistics' , locals: {employees: @employees} %>');

app/views/employees/destroy.js.erb
$('#employee_<%= @employee.id %>').fadeOut(function() {$(this).remove()});
$('#salary_statistics').replaceWith('<%= j render partial: 'employees/partials/statistics', locals: {employees: @employees}  %>');

app/views/employees/edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
      <h4 class="modal-title custom_align" id="Heading">Edit employee</h4>
    </div>
    <div class="modal-body">
      <%= render partial: 'employees/partials/form', locals: {employee: @employee,
                                                                departments: @departments} %>
    </div>
  </div>
  <!-- /.modal-content -->
</div>

app/views/employees/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>All Employees</h3>
      <p>
        <button style="margin-bottom: -10px" type="button" id="new_employee" class="btn btn-primary mybuttons">Create
          new employee
        </button>
      </p>

      <div style="margin-bottom: -10px; margin-top: 30px">
        <%= render partial: 'employees/partials/statistics', locals: {employees: @employees} %>
      </div>

      <%= link_to cut_employees_path(@employees.pluck(:id)), method: :post, remote: true do %>

          <button type="button" class="btn btn-warning mybuttons">Cut all salaries</button>

      <% end %>

      <div class="table-responsive">
        <%= render partial: 'employees/partials/employee_table', locals: {employees: @employees} %>
      </div>
    </div>
  </div>
</div>

<div id="employee_modal" class="modal fade" role="dialog"></div>

app/views/employees/new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
      <h4 class="modal-title custom_align" id="Heading">Create new employee</h4>
    </div>
    <div class="modal-body">
      <%= render partial: 'employees/partials/form', locals: {employee: @employee,
                                                                departments: @departments} %>
    </div>
  </div>
  <!-- /.modal-content -->
</div>

app/views/employees/partials/_employee.html.erb
<tr id="employee_<%= employee.id %>">
  <td><%= employee.name %></td>
  <td><%= employee.address %></td>
  <td><%= '%.2f' % employee.salary rescue '' %></td>
  <td><%= link_to employee.department.company.name, company_departments_path(employee.department.company) if employee.department.present? && employee.department.company.present? %></td>
  <td><%= link_to employee.department.name, department_employees_path(employee.department) if employee.department.present? %></td>
  <td>
    <% if url_for.include? 'departments' %>
        <%= link_to cut_department_employees_path(department_id: employee.department.id, format: employee.id), method: :post, remote: true do %>
            <p data-placement="top" data-toggle="tooltip" title="Cut">
              <button class="btn btn-warning btn-xs">
                <span class="glyphicon glyphicon-scissors"></span></button>
            </p>
        <% end %>
    <% else %>
        <%= link_to cut_employees_path(format: employee.id), method: :post, remote: true do %>
            <p data-placement="top" data-toggle="tooltip" title="Cut">
              <button class="btn btn-warning btn-xs">
                <span class="glyphicon glyphicon-scissors"></span></button>
            </p>
        <% end %>
    <% end %>
        </td>
        <td>
          <p data-placement="top" data-toggle="tooltip" title="Edit">
            <button class="btn btn-primary btn-xs" id="edit_employee_<%= employee.id %>">
              <span class="glyphicon glyphicon-pencil"></span></button>
          </p>
        </td>
        <td>
          <%= link_to employee, method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
              <p data-placement="top" data-toggle="tooltip" title="Delete">
                <button class="btn btn-danger btn-xs">
                  <span class="glyphicon glyphicon-trash"></span></button>
              </p>
          <% end %>
        </td>
        </tr>
        <script>$(function () {
          var $modal = $('#employee_modal');
          $('#edit_employee_<%= employee.id %>').on('click', function () {
            $modal.load('<%= edit_employee_path(employee) %>', '', function () {
              $modal.modal();
            });
          });
        });</script>

app/views/employees/partials/_employee_table.html.erb
<table id="employee_table" class="table table-bordred table-striped">

  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Salary</th>
    <th>Company</th>
    <th>Department</th>
    <th>Cut</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>

  <% employees.order(name: :asc).each do |employee| %>
      <%= render partial: 'employees/partials/employee', locals: {employee: employee} %>
  <% end %>

  </tbody>

</table>

<script>$(function () {
  var $modal = $('#employee_modal');
  $('#new_employee').on('click', function () {
    $modal.load('<%= new_employee_path %>', '', function () {
      $modal.modal();
    });
  });
});</script>

app/views/employees/partials/_form.html.erb
<%= form_for employee, remote: true, html: {id: 'employee_form'} do |f| %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
      <span class="help-block"></span>
    </p>
    <p>
      <%= f.label :address %><br/>
      <%= f.text_field :address %>
    </p>
    <p>
      <%= f.label :salary %><br/>
      <%= f.text_field :salary %>
      <span class="help-block"></span>
    </p>
    <p>
      <%= f.label :department_id %><br/>
      <%= f.select :department_id, options_from_collection_for_select(departments, :id, :name, f.object.department_id), include_blank: '' %>
    </p>
    <p>
      <%= f.submit nil, class: 'btn btn-warning' %>
    </p>

<% end %>
<script>
  $(function () {
    var $form = $('#employee_form');
    $form.validate({
      rules: {
        "employee[name]": {
          required: true
        },
        "employee[salary]": {
          number: true
        }
      },
      errorPlacement: function (error, element) {
        $(element).closest('p').find('.help-block').text(error.text());
      },
      highlight: function (element) {
        $(element).closest('p').removeClass('has-success');
        $(element).closest('p').addClass('has-error');
      },
      unhighlight: function (element) {
        $(element).closest('p').removeClass('has-error');
      },
      success: function (element) {
        $(element).closest('p').addClass('has-success');
      }
    });
  });
</script>

app/views/employees/partials/_statistics.html.erb
<div id="salary_statistics">
<h4>Total salaries: <%= '%.2f' % get_total_salaries(employees) %></h4>
<h4>Mean salary: <%= '%.2f' % get_mean_salary(employees) %></h4>
</div>

app/views/employees/update.js.erb
$('#employee_modal').modal('hide')
$('#employee_<%= @employee.id %>').replaceWith('<%= j render partial: 'employees/partials/employee', locals: {employee: @employee} %>')
$('#salary_statistics').replaceWith('<%= j render partial: 'employees/partials/statistics', locals: {employees: @employees} %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompanyManager</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="header" class="navbar navbar-fixed-top">
  <div id="header-container" class="container navbar-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="brand" class="navbar-brand" href="#">CompanyManager</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', welcomes_index_path %></li>
        <li><%= link_to 'Companies', companies_path %></li>
        <li><%= link_to 'Departments', departments_path %></li>
        <li><%= link_to 'Employees', employees_path %></li>
        <li><%= link_to 'About', abouts_index_path %></li>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/welcomes/index.html.erb
<div class="container">
  <h2 class="text-center" style="margin-bottom: 50px">Welcome to CompanyManager</h2>
  <div class="text-center">
    <%= image_tag('homepage.jpg', size: '960x555') %>
  </div>
</div>